### ISSUE TITLE
invalid literal for int() при запуске

### ISSUE THREAD

**Issue by k0st1x** [CLLlAgOB/free2fa4rdg#1]
запускаю docker compose up и получаю в output:

   File "/app/config.py", line 33, in Config
free2fa4rdg_api-1         |     FREE2FA_TIMEOUT = int(os.environ.get("FREE2FA_TIMEOUT", 10))\
 ValueError: invalid literal for int() with base 10: ''

**Comment by CLLlAgOB** [comment]
А что у вас в файле (.env)?

**Comment by k0st1x** [comment]
FREE2FA_TIMEOUT там не задан. Странно, что падает

**Comment by CLLlAgOB** [comment]
Задайте на 20. Вообще странно что не задан. По идее если вы не указали ничего(нажали просто энтер) то он должен был прописаться со значением по умолчанию. Возможно вы нажали пробел и энтер?
